src/gui.cxx
Quick fix meant for UK/Ireland keyboard layouts because 
`@` and `#` symbols are replaced by `"` and `£` on them.
=> Add hotkey symbols for en-GB layout

resources/metadata/luppp.desktop
I'm quite sure that the version thing is non needed. Please correct me if I'm wrong.
A little French line improvement.
The icon place is up to the packager I guess. That said, I'm not sure it doesn't conflict with a personal compilation. If that can be helpful, I know that in Debian, the icons are to be put under /usr/share/pixmaps/ .
Hope that helps and, please @harryhaaren, feel free to ask some change to this PR.
=> updates desktop file

src/diskreader.cxx
The pan dial uses values of the interval [-1, 1]. These values are converted to an interval of [0, 1] by gtrack.hxx:70. When reading pan values from a saved file, a reversed conversion needs to be done.
This is currently not the case but will be done by this PR. It fixes #168.
=> Fix loading of pan values

README.md
It took me a while to find this. It should also be linked from the [Lupp web page](http://openavproductions.com/luppp/).
=> put link to user documentation at top of README.md

meson.build, meson_options.txt, src/avtk/meson.build, src/cjson/meson.build, src/controller/meson.build, src/dsp/meson.build, src/meson.build, src/observer/meson.build, src/state/meson.build, src/tests/meson.build, src/version.hxx.in
This PR enables Luppp to be built with Meson. The build files are simpler and much more readable than CMake, which should ensure builds are more consistent and that testing of builds with its options is better covered.
=> Add Meson build system integration

src/config.hxx, src/gmastertrack.cxx
Alright, i thought about a little and this is my solution. 
There are two "features" included here:
- change limits for possible bpm-value in config.hxx (first commit)
- check if custom bpm value is in the limit (second commit)
The third commit is needed because if you enter values <60 or >220, it just dont work without any user feedback. I dont know if this string-stuff is "nice" coded, but its working. if there are any complains about (eg speed or something) please let me know. (Sadly i dont have internet access and cant get into the topic at the moment).
Maybe it would be an good idea to tell the user if the input is "wrong", but i didnt wanted to let the popup pop up again and as far as i can see there is no implemented way to tell the user that something gone wrong, is it?
Happy if …
=> Sanity check for bpm input

src/controller/genericmidi.cxx, src/timemanager.cxx
self explaining. But by the way, what is meant by this "ZeroOne" stuff? There is an FIXME:
// FIXME: quick-fix for "ZeroOne" type value -> BPM range
maybe this is already resolved?
=> found two more hard coded bpm limits

src/avtk/avtk_unit.h, src/avtk/clipselector.cxx, src/avtk/clipselector.hxx, src/looper.cxx, src/looper.hxx
In this PR i replaced all hard coded Scene numbers by NSCENES from the config.h. This way the number of tracks and scenes can be changed on compile time. 
This is the first step in getting luppp running with custom number of tracks and scenes. Currently, it is working, but the GUI gets wrong. But this should be another, following PR. I hope i found all hard coded numbers, but luppp seems to work with custom values so i guess i found everything. I also searched for 8 and 10 in the hole repository and replaced everything. 
There is just one file left: /home/georg/workspace/openAV-Luppp/src/tests/lupppTestMaterial/lupppTest/session.luppp which contains hard coded number of sceneNames and tracks. But there is no easy way to repair this. (In this moment it gets in my mind to try to load this …
=> Replace all hard coded scene numbers

src/controller/binding.hxx, src/jack.cxx
Since the active fields need to be `-1` for clearing a clip, we took away the ability to set active to an illegal value. Thats why we need another default value, and i think the best would be the normal grid event like it was before. So i set this to `1`, which fixes #134
=> sets default binding active to 1

src/config.hxx, src/jack.cxx, src/jacksendreturn.cxx, src/looper.cxx, src/trackoutput.cxx
This PR adresses #220. 
To explain: When we/someone built the stereo signal chain in luppp, the way to access buffers needed to change. Before stereo, we could simply do `buffer[ first_track + current_track]`. But since there are two Buffers for each track, eg Left and Right, we need to skip 2 buffers for each track. This PR changes all buffer reads to go this way: `buffer[ first_track + current_track * 2]`
We could also change the order of the buffers in buffers.hxx to
track_1_l
track_2_l
...
track_1_r
track_2_r
but this PR seems to be the better solution for me.
Thanks to @coderkun for the help.
Before we merge i would like to have some more tests from other users.
=> repair trackconfusion

src/jack.cxx, src/jack.hxx, src/looper.cxx
This PR adresses #228. 
The first commit prevents the input getting piped to the Sends if the Mix-Button is turned off. From my point of view it does not make any sense to apply an effect to a signal you dont hear at the moment. 
The second commit applys the input volume fader also to the recordings, so you can adjust the volume of the recorded clips.
These are not so big changes, i did some testing and everything should work. So this should be ready for merging.
=> Fix Input Signal Flow

src/looper.cxx, src/looper.hxx, src/looperclip.cxx, src/looperclip.hxx, src/metronome.cxx, src/metronome.hxx, src/observer/time.hxx, src/timemanager.cxx, src/timemanager.hxx
@harryhaaren this is now nearly perfect, I have offsets <1 sample on bar-reset. There might be some small issues left with resetting, but this should be an easy fix. Would be great to have this merged asap so our beloved power users are able to check if this is working
=> calculate tempo related numbers on higher precision

src/config.hxx, src/jack.cxx, src/jack.hxx, src/jacksendreturn.cxx, src/jacksendreturn.hxx, src/trackoutput.cxx, src/trackoutput.hxx
(+ one continuous i forgot :upside_down_face: )
This is the last PR for smoothing out all controls in Luppp. Until now this is only implemented for the FX-Buttons. So todo is:
- Snd-Buttons
- Key-Buttons (usually no one should hear this signal but for sure)
- Input Mix-Button
But i wont make this today and wanted to upload to get early feedback.
=> Smoothing for discrete controls

src/tests/qunit.hxx
This removes auto open of the failed assert, which was
a fancy feature but pretty darn hacky too.
Signed-off-by: Harry van Haaren <harryhaaren@gmail.com>
=> tests: remove auto open file at failure

src/avtk/clipselector.cxx, src/eventhandlergui.cxx
@harryhaaren This is a proposal to fix the issue we talked about last night. The idea came to me this morning, I don't know if this is a sane solution. So please have a look and decide, if this seems to be okay. 
In general it would be a good idea to redesign how the GUI is build in this aspect, handling scenes and clips with the same class is obviously possible but also is kind of hacky.
=> prevent scene names being cleared on scene launch

src/avtk/avtk_dial.h
Before this the pan_style value was not initialized,
meaning that the dial could (very rarely) appear as
a pan style dial when it should not be. Thanks valgrind :)
Signed-off-by: Harry van Haaren <harryhaaren@gmail.com>
=> dial: fix unitialized variable

src/goptions.cxx, src/timemanager.cxx
This commit adds a bpm conversion from the fpb to set the
tempo to, and then limits the values to the range as set
in config.hxx. A message is safely printed to the console
when a message is dropped. Fixes #240.
Signed-off-by: Harry van Haaren <harryhaaren@gmail.com>
=> timemanager: error check tempos from "Use Tempo"

.clang-format
This is a starting point about a discussion about how to style the code. 
I tried to get as near as the current style, but there are some differences, eg Constructor Initialisation lists which will look like this:
```
GenericMIDI::GenericMIDI(std::string file)
: Controller()
, MidiIO() {
```
I dont think this is optimal, but clang-format seems to be a little restricted at this point.
Anyway, if you want to style a file, you will need this command (Although you should make your editor doing this):
```clang-format -i filename```
To test, i simply formatted files with this settings and viewed the git diffs.
There might be some stuff to discuss, eg line length, indention. So please test what this configuration does and tell me if you are happy.
=> added proposal for .clang-format

src/jack.cxx, src/jack.hxx, src/jacksendreturn.cxx
When using Pipewire, Luppp does not get updated when changing the Frames/Period setting in the Pipewire-&gt;Jack server. This may also be the case when using regular Jack - not sure. In fact, before this change, when using Pipewire, it would only adhere to the maximum quantum in Pipewire, and changing settings in the Pipewire-&gt;Jack server would make Luppp change the "pace" in which it goes through the BPM (e.g., 1024 frames/period results in 120 BPM but 512 frames/period feels like 240 BPM, even though Luppp reports 120 BPM).
I implemented jack_set_buffer_size_callback into Luppp so that when the buffer size is changed externally, it gets updated, and everything works as intended.
Just one thing I'm not sure about is the part in `src/jacksendreturn.cxx` that I have commented out. …
=> Jack buffersize is updated when changed after Luppp has loaded

src/jack.cxx
Small change to notify the user why LUPPP has crashed when JACK it's buffer size is set over 1024.
=> When JACK buffer size is set above 1024 LUPPP crashes on start
